# Generated by Django 5.2.6 on 2025-11-10 01:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_booking_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'event', 'is_cancelled', 'cancelled_at')},
        ),
    ]
