# Generated by Django 5.2.6 on 2025-11-10 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_booking_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'event')},
        ),
        migrations.AddField(
            model_name='booking',
            name='participants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
    ]
